### ISSUE TITLE
No graph data when module is renamed

### ISSUE THREAD

**Issue by Danbr4d** [trisyoungs/duq#1594]
Dissolve lets you rename analysis modules but when they are renamed, the data does not seem to be showing up on the graphs in the module.
I have tried this for HistogramCN and Angle and IntraDistance with the same effect. I run the module first and data is printed on the graph, then I renamed the module, cleared the data and ran the simulation again but this time no data appeared on the graph.
I ran this on IDAaaS.

**Comment by trisyoungs** [comment]
@Danbr4d  This should be a relatively straightforward case of signalling the module to `RecreateRenderables` whenever the module name is changed.  That particular "signal" is sent off when specific keywords defined in a module have their value changed, but we can definitely use it for the same purpose here.
