### ISSUE TITLE
Assigning Values to PRs

### ISSUE THREAD

**Issue by trisyoungs** [trisyoungs/duq#1651]
### Overview

In order to capture some metric of the "effort" we put into Dissolve, I'm suggesting that we enforce that an "effort number" be assigned, as a label,  to each and every PR we put in (blocking merge if one is not present). The descriptors against "effort value" below deliberately avoid any notion of time, since the individual skill levels of project contributors determine how long it takes to solve a particular problem, and we focus instead from the point of view of the codebase.

This is, I want to stress, not a thinly-veiled attempt at any sort of judgement of, or comparison between, individual contributors. From the perspective of resourcing the project, it is extremely useful to quantify the project in terms of effort done vs effort remaining, and hence justify further effort required.  This is a free and open forum, so please feel free to discuss / push back on this, either here or via our Teams channel.

#### Effort Descriptors
- `1` Trivial fix - correct a comment, newline, typo etc.
- `2` Easy task : Small number of lines of code, minor brainpower used, e.g. simple fixes, easy renaming / refactoring etc.
- `4` Small task : A localised change or addition to the code up to approx. 100 lines, or a distributed set of smaller changes across the code amounting to the same.
- `8` Medium task : A significant localised change or addition (e.g. a new `ProcedureNode` or simple `Module`), or a larger refactoring across many files.
- `16` Large task : A larger piece of work encompassing a sizeable feature implementation or in-depth refactor of the codebase.
-  `32` Major task : Best illustrated as a large task that takes a significant amount of effort in order to implement, e.g. due to encountering unforseen blockers or difficulties in implementation.
- `64` Huge task : Avoided if at all possible.

**Comment by jws-1** [comment]
Alongside this, maybe we should use the same effort descriptors for issues (I see that they already exist).

**Comment by trisyoungs** [comment]
Closing as "not going to do this"!
