### ISSUE TITLE
Qt AutoMoc

### ISSUE THREAD

**Issue by trisyoungs** [trisyoungs/duq#1733]
**Describe the feature / issue**
We don't, for historical reasons lost to the sands of time, use Qt's automoc option in our `cmake` chain.  This is fine, but leads to deliberate naming of files like `myWidgetFuncs.cpp` in order to avoid clashes with Qt-generated `myWidget.cpp` from a ui file, but using automoc this isn't required and would tidy up our naming a bit.

**Comment by rprospero** [comment]
using automoc will also simplify the QML toolchain
