### ISSUE TITLE
Multiline error messages are not printed in their entirety

### ISSUE THREAD

**Issue by trisyoungs** [trisyoungs/duq#1822]
**Describe the bug**
The `Messenger::error` function does not correctly parse and print multiline messages. For example:
```
Messenger::error("This is part 1.\nAnd this is part 2.");
```
Only "This is part 1." is printed:
```
***  ERROR
***  ERROR This is part 1.
***  ERROR
```

**Comment by rprospero** [comment]
After a bit of testing, we do _mostly_ print multi-line messages correctly.  It is only the last line which is skipped.
