### ISSUE TITLE
Trajectory output Atom Types 

### ISSUE THREAD

**Issue by shrmiao** [trisyoungs/duq#1890]
**Describe the feature / issue**
Accumulated trajectory files can be very useful for post-dissolve analysis and it is a good way to make sure various analysis are performed over the same geometry/energy landscape. Currently, the output trajectory file only contains 4 columns: Element, X-coord, Y-coord, Z-coord.

I think it would be more useful to output: Atom Type, X-coord, Y-coord, Z-coord; so that sites can be differentiated among functional groups (i.e. hydroxyl hydrogen and alkyl hydrogen).

If possible, I think it would be even better if the output could include 6 columns: Element, Atom Type, Atom Index (within the species), X, Y, Z

As an example (2 water molecules per frame):

6 (total number of atoms in 1 frame)
blah blah (box name)
H     Hw     1     X     Y     Z
H     Hw     2     X     Y     Z
O     Ow     3     X     Y     Z
H     Hw     1     X     Y     Z
H     Hw     2     X     Y     Z
O     Ow     3     X     Y     Z
6
blah blah
...

**Comment by rprospero** [comment]
@shrmiao @trisyoungs Would it be acceptible to have the columns be

1. Element
2. X
3. Y
4. Z
5. Atom Type
6. Atom Index

I mostly ask because this would keep the first four columns in their original order in the case where users already have scripts for analysing these files?

**Comment by shrmiao** [comment]
I actually wrote codes based on the first 4 columns too so keeping them the same would be a good idea :)
