### ISSUE TITLE
Min/max distance restraints

### ISSUE THREAD

**Issue by danielirvingdls** [trisyoungs/duq#1982]
I'm trying to get back into the X-ray total scattering refinement world via Dissolve and one thing that would be particularly helpful for me and I used **a lot** in EPSR was the min/max distances (npairspcof). Is that something that will be implemented in some way into Dissolve? Whether it is via the same routes or a new route, it would be useful from the X-ray perspective where we don't have the scattering for weak X-ray systems (hydrogens are hard for us!) and the LJ doesn't have the power to make sure things don't get too close.

**Comment by danielirvingdls** [comment]
I've actually just noticed the restraintPotential which work to an extent but being able to specify atom types within the system would be great (Ow in water and ion rather than full species)

**Comment by trisyoungs** [comment]
One might argue that sensible LJ+charge parameters should always prevent bad overlaps - however, and particularly with hydrogens on hydroxyls etc., this isn't always the case!  You can probably achieve what you want with pair potential overrides in Dissolve, which more-or-less amounts to the same thing.  In the Pair Potentials tab in the Forcefield you can find an "Overrides" section at the bottom left. There you can add as many atom-type-name-specific additional potentials of various functional forms - these are added on top of the defined LJ+q terms in the tabulation.  You can also use the `*` wildcard in the names of the two target atomtypes.

**Comment by danielirvingdls** [comment]
Perfect, that's exactly what I was looking for but not looking in the right places! Thanks Tris
