### ISSUE TITLE
Crash when reloading input file from unsaved state

### ISSUE THREAD

**Issue by tfheaden** [trisyoungs/duq#788]
**Describe the bug**
Crash when reloading input file from unsaved state

**To Reproduce**
Steps to reproduce the behaviour (if necessary):
Make changes in dissolve somewhere (added a new species in this case, but may be more general).
Wanted to discard changes so went to reload input file. File > Open local > click No > Chose input file > clicked open > Crash

**Operating System:**
 - OS:   Linux  (IDAaaS), using Dissolve 0.8.2

**Comment by trisyoungs** [comment]
Confirmed.  Exposes an issue with tab management in the main UI.  Fix pending in 0.8.3.
